name: cypherflutter
description: A new Flutter project.


publish_to:


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  firebase_auth: ^4.2.1
  flutter_login: ^4.1.1
  quickalert: ^1.0.1
  firebase_core: ^2.4.0
  firebase_database: ^10.0.7
  font_awesome_flutter: ^10.3.0
  local_auth: ^2.1.3
  flutter_secure_storage: ^7.0.1
  open_settings: ^2.0.2
  flutter_local_notifications: ^13.0.0
  awesome_notifications: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#12CDEC"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - lib/icons/
    - assets/motion.png
    - assets/logo_foreground.png
    - assets/noti.png


